In [1]:
import pandas as pd
import numpy as np 
import sqlite3

In [11]:
df = pd.read_csv('~/Desktop/TechnicalTask/dataset/dataset.csv', index_col=None)
df.head()

,Order Date,Purchase Order,Customer ID,Customer Location,Order Req Amt (Ton),Fullfilled By ID,Fullfilled By Location,Supplied Amt (Ton),Cost Of Delivery ($)
0,02/10/21 01:11,50f43343-e930-4f2e-91be-606bc018c872,c53fa27e-c8c2-4b77-a89a-6ed11fa87317,Cincinatti,203,19f4a11d-63ca-4127-975a-15933aaa33ff,Omaha,203,2233
1,02/10/21 04:17,cb06e4cc-5469-4e30-a92f-287ae4a62896,d20009ca-5479-4232-8b07-7c8c11f74c2e,St Louis,127,cf9651b0-df49-498f-a66c-0a7f897545ce,Kansas City,127,1016
2,02/10/21 04:43,a23e6eb8-8a52-434b-b35c-5c1d3a70b0ea,70080304-afa3-4026-9c86-95970c4ed5b4,Chicago,242,ae5d7b77-86c9-49d2-ac18-09bf9883adc2,Des Moines,210,840
3,02/09/21 03:26,cd5fdc3d-b08f-426e-bc9e-fb25a676d2be,c53fa27e-c8c2-4b77-a89a-6ed11fa87317,Cincinatti,188,cf9651b0-df49-498f-a66c-0a7f897545ce,Kansas City,188,1880
4,02/09/21 05:08,90474d73-46c2-4e7a-a42e-27907d13fe48,70080304-afa3-4026-9c86-95970c4ed5b4,Chicago,154,19f4a11d-63ca-4127-975a-15933aaa33ff,Omaha,154,1078

In [25]:
Order_Product = df.drop(['Order Date', 'Order Req Amt (Ton)', 'Customer ID','Customer Location'], axis=1)
Purchase_Order = df.drop([ 'Supplied Amt (Ton)', 'Fullfilled By ID','Fullfilled By Location', 'Cost Of Delivery ($)'], axis=1)
Supplier = df.drop(['Order Date', 'Purchase Order', 'Order Req Amt (Ton)','Supplied Amt (Ton)', 'Cost Of Delivery ($)','Customer ID','Customer Location'], axis=1)

Order_Product
Supplier
Purchase_Order

,Order Date,Purchase Order,Customer ID,Customer Location,Order Req Amt (Ton)
0,02/10/21 01:11,50f43343-e930-4f2e-91be-606bc018c872,c53fa27e-c8c2-4b77-a89a-6ed11fa87317,Cincinatti,203
1,02/10/21 04:17,cb06e4cc-5469-4e30-a92f-287ae4a62896,d20009ca-5479-4232-8b07-7c8c11f74c2e,St Louis,127
2,02/10/21 04:43,a23e6eb8-8a52-434b-b35c-5c1d3a70b0ea,70080304-afa3-4026-9c86-95970c4ed5b4,Chicago,242
3,02/09/21 03:26,cd5fdc3d-b08f-426e-bc9e-fb25a676d2be,c53fa27e-c8c2-4b77-a89a-6ed11fa87317,Cincinatti,188
4,02/09/21 05:08,90474d73-46c2-4e7a-a42e-27907d13fe48,70080304-afa3-4026-9c86-95970c4ed5b4,Chicago,154
...,...,...,...,...,...
163,25/04/17 15:53,18487038-b8a9-424e-9096-35807fb8ef57,70080304-afa3-4026-9c86-95970c4ed5b4,Chicago,136
164,26/04/17 02:54,f34be0a5-2364-4945-a3d0-027f6e34f2ee,c53fa27e-c8c2-4b77-a89a-6ed11fa87317,Cincinatti,197
165,26/03/17 18:10,2c713247-b860-40e8-9832-04789ad61a7c,c53fa27e-c8c2-4b77-a89a-6ed11fa87317,Cincinatti,349
166,27/03/17 04:54,056cb0d9-599d-4492-ae44-a2ca70f54b6d,d20009ca-5479-4232-8b07-7c8c11f74c2e,St Louis,132
167,27/03/17 06:00,f577ed6e-d6ff-4ace-9133-15adc6e0eaa5,70080304-afa3-4026-9c86-95970c4ed5b4,Chicago,111

In [26]:
Supplier.to_csv('Supplier.csv', index=False)
Order_Product.to_csv('Order_Product.csv', index=False)
Purchase_Order.to_csv('Purchase_Order.csv', index=False)

In [46]:
import sqlite3
import csv

conn = sqlite3.connect("Broker.db")
cur = conn.cursor()

cur.execute(""" 
CREATE TABLE Purchase_Order
('Order date' date,
'Purchase Order' varchar(36) NOT NULL,
  'Customer ID' varchar(32), 
  'Customer Location' varchar(32),
'Order Req Amt (Ton)' int NOT NULL,
FOREIGN KEY('Customer ID') REFERENCES Customer('Customer ID'),
 PRIMARY KEY('Purchase Order')
); """)

cur.execute(""" 
CREATE TABLE Supplier
('Fullfilled By ID' varchar(36) NOT NULL,
Fullfilled By Location varchar(30),
 PRIMARY KEY('Fullfilled By ID')
); """)


cur.execute(""" 
CREATE TABLE Order_Product
('Purchase Order' varchar(36) NOT NULL,
'Fullfilled By ID' varchar(36) NOT NULL,
'Fullfilled By Location' varchar(32),
'Supplied Amt (Ton)' int NOT NULL,
'Cost Of Delivery ($)' int NOT NULL,
FOREIGN KEY('Purchase Order') REFERENCES Purchase_Order('Purchase Order'),
FOREIGN KEY('Fullfilled By ID') REFERENCES Supplier('Fullfilled By ID'),
FOREIGN KEY('Fullfilled By Location') REFERENCES Supplier('Fullfilled By Location'),
PRIMARY KEY ('Purchase Order','Fullfilled By ID')
); """)

conn.commit()

purchase = open('Purchase_Order.csv')
order = open ('Order_Product.csv')
supplier = open('Supplier.csv')


with open('/Users/Yahnik/Desktop/Blueprism/Purchase_Order.csv', 'r') as file:
    no_records = 0
    for row in file:
        cur.execute(
           "INSERT INTO Purchase_Order VALUES(?,?,?,?,?)", row.split(","))
        conn.commit()
        no_records += 1
print('\n{} Records Transferred'.format(no_records))


with open('/Users/Yahnik/Desktop/Blueprism/Order_Product.csv', 'r') as file:
    no_records = 0
    for row in file:
        cur.execute(
           "INSERT INTO Order_Product VALUES(?,?,?,?,?)", row.split(","))
        conn.commit()
        no_records += 1
print('\n{} Records Transferred'.format(no_records))


with open('/Users/Yahnik/Desktop/Blueprism/Supplier.csv', 'r') as file:
    no_records = 0
    for row in file:
        cur.execute(
           "INSERT INTO Supplier VALUES(?,?)", row.split(","))
        conn.commit()
        no_records += 1

print('\n{} Records Transferred'.format(no_records))
conn.close()

169 Records Transferred

169 Records Transferred

IntegrityError: UNIQUE constraint failed: Supplier.Fullfilled By ID

In [48]:
select_all = "SELECT * FROM Purchase_Order"
rows = cur.execute(select_all).fetchall()

for r in rows:
    print(r)
 
# Committing the changes
connection.commit()

('Order Date', 'Purchase Order', 'Customer ID', 'Customer Location', 'Order Req Amt (Ton)\n')
('02/10/21 01:11', '50f43343-e930-4f2e-91be-606bc018c872', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 203)
('02/10/21 04:17', 'cb06e4cc-5469-4e30-a92f-287ae4a62896', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 127)
('02/10/21 04:43', 'a23e6eb8-8a52-434b-b35c-5c1d3a70b0ea', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 242)
('02/09/21 03:26', 'cd5fdc3d-b08f-426e-bc9e-fb25a676d2be', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 188)
('02/09/21 05:08', '90474d73-46c2-4e7a-a42e-27907d13fe48', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 154)
('02/09/21 06:05', 'd432dbd7-bf0b-4fd2-b56d-00d06baec1b5', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 102)
('02/08/21 13:04', '179e4d09-11a6-4659-a380-a6ef3103e495', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 307)
('02/08/21 14:28', 'a1944fe4-f8fa-4a76-a290-6bbc5994aa28', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 129)
('02/08/21 20:39', 'd35d6abf-ad37-4404-b163-3c18d557f0f9', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 139)
('03/07/21 16:59', '43567602-e2bb-4c86-aa1c-10675e9c34e6', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 93)
('04/07/21 04:49', '4d76c1cd-5458-4cac-be5a-d7f31c3fd2c2', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 130)
('04/07/21 05:49', 'fa014ec9-1b59-4115-b959-119da3fc0c20', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 230)
('03/06/21 21:59', 'd69290b7-3989-4efb-a9ac-4063a6a51c78', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 126)
('04/06/21 04:35', 'f28615ea-7065-41e2-9f55-1d15d6a5f6ce', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 294)
('04/06/21 05:59', 'f5d4062b-a66b-40b7-88f5-4cf0ccdb9fad', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 275)
('04/05/21 20:13', 'fca66ae5-dea5-4b87-a865-53122d9db98a', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 161)
('05/05/21 01:27', '9bf5f019-b674-4869-95cf-50574958a532', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 347)
('05/05/21 04:45', '09350ed1-09a2-4223-a27c-ce6a96a0f220', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 102)
('04/04/21 13:19', '1c408c9c-508a-48db-a6bd-0245e846c33b', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 127)
('04/04/21 18:34', '733ace4c-05a6-4909-b00d-6246245fe06e', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 426)
('05/04/21 00:19', '81298777-ace9-47f3-8fb8-7466aae330b3', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 138)
('05/03/21 18:24', 'f5d08502-3ad6-4b08-ae40-8bc993a04ac4', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 182)
('06/03/21 02:41', '5a7bd64a-06a7-42cb-b34a-9b27e52cb013', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 249)
('06/03/21 03:04', '2a665f4e-e51d-4b06-8040-4c63ab4487b4', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 85)
('03/02/21 15:58', 'e5b015b8-9534-4787-98a6-17b038e7eed6', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 157)
('04/02/21 04:16', 'a6de9929-db3d-475b-a6e5-972d8f40a8b9', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 133)
('04/02/21 05:08', '4cb944cd-9049-479d-ab8e-33b13126fec1', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 195)
('05/01/21 03:51', '9293865f-4a76-4435-b8d6-087692fb4f54', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 201)
('05/01/21 04:26', 'cd0d5365-4e0f-4fa9-9b00-47d420313995', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 78)
('05/01/21 05:54', 'ca1877a6-5c84-4153-a812-afdb25f9b7eb', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 192)
('05/12/20 17:09', '70a24878-bb5d-44e1-9d15-58b2a9ecc3d5', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 149)
('06/12/20 03:20', 'e3e00921-9c29-488b-b127-72ce5a83ce15', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 163)
('06/12/20 03:43', '60e058c2-885b-4f6f-9e94-429979af5eef', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 73)
('05/11/20 10:50', 'e181f8f4-d517-4c81-b73d-4e201867dd20', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 185)
('05/11/20 13:29', '0466ebc5-faef-4d5a-94e9-a5260d8ab396', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 292)
('05/11/20 18:18', '000ad40c-a1d4-4701-9790-2c3e9e591bec', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 134)
('06/10/20 08:44', '6b03024e-5c59-4ef9-b01c-74b2a5e9f306', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 187)
('06/10/20 13:28', 'b6222810-af88-40f4-9f40-686abc3cbed5', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 297)
('07/10/20 03:24', '6d10cbd9-b7ef-4d16-ab26-dbecf918dc91', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 144)
('06/09/20 19:42', 'a9cf700c-89f2-4a34-bd95-b7ca4fc90e78', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 317)
('07/09/20 01:25', 'e3bcf02a-8708-4f4c-9f8b-dd73c0469f57', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 78)
('07/09/20 02:59', 'e88b928c-0c70-474b-ac99-2d9f088da4ef', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 186)
('07/08/20 11:10', 'b1a8dee5-afa3-43e2-be8a-20fd5185fa1e', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 86)
('07/08/20 21:20', 'd871b579-d171-434e-91cc-dfb97e123a13', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 236)
('08/08/20 06:00', 'bef304f7-d0a2-458f-b5de-ba61a0addb13', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 163)
('08/07/20 10:51', '10aab08d-471c-4c14-a83b-4fcd7aeb9696', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 52)
('08/07/20 18:58', '1bd2c778-1456-4884-b0fc-e7985d4a38fd', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 251)
('08/07/20 23:40', '9b8cefe0-610f-4f65-a795-fb0a3f4a181e', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 283)
('08/06/20 09:11', '83bc6dae-2124-4f59-ae4c-5fde14a8bf53', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 73)
('09/06/20 01:31', 'd200a121-4ef1-4779-b30f-a80e7412b7d8', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 435)
('09/06/20 01:49', '28b629c0-add5-4548-ace9-bab3d0f9e4fa', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 197)
('09/05/20 17:12', 'aa299990-2fa5-4061-9647-08f69878e78a', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 443)
('10/05/20 01:53', 'af902384-358d-42fa-b343-339b688c6a9d', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 62)
('10/05/20 02:16', '5081b04f-e3b0-4b4a-b00b-6bb2831e0b01', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 258)
('09/04/20 20:12', 'd0178950-ea94-4596-a9f0-36a0c9562169', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 130)
('10/04/20 01:36', '4e37404f-9ab3-462f-af41-fe34169dfc96', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 409)
('10/04/20 02:40', '41b54250-7dba-4cfd-bf73-3dfdd672b5fd', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 177)
('11/03/20 05:50', '6c86f314-cdc3-47c6-866f-a9fe4a19bab6', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 137)
('11/03/20 06:00', '3d8497bf-a69a-4c60-a8a0-4d460d7a3503', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 78)
('11/03/20 06:02', 'a2682e8d-0545-4e07-a4f9-d7476ad3bbbb', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 377)
('09/02/20 12:05', '8ba5c9f6-0f2a-48f5-915f-45098946387f', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 272)
('09/02/20 18:35', '80c3378d-17ae-4c56-999e-606fecc6c961', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 270)
('10/02/20 05:00', '9f7f61fc-1296-46d4-b55a-0da4c5adbeae', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 139)
('10/01/20 11:15', '6adc40a7-7a53-492f-8d45-be7c5e1c4835', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 133)
('10/01/20 14:02', '7e391326-fbb4-42b5-a62f-b4a7f1b6a83e', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 160)
('10/01/20 21:38', '72b07847-ab62-4748-ad96-87c3c9e96a1d', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 272)
('11/12/19 14:21', 'dbd8cb4e-a75a-401e-83a8-f0c1341b72a7', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 404)
('11/12/19 16:41', '1eb9b50a-58ce-4d00-b2dd-3c4a8e807c6a', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 128)
('11/12/19 18:20', 'd86e2e0a-b2df-452b-92c1-18cd9d28be74', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 140)
('11/11/19 20:45', 'a4e4e90e-5932-4232-967c-0d34e23ee2fc', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 101)
('12/11/19 05:08', 'a45a330c-e1aa-48d1-bfc8-b9eed7ddda1e', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 227)
('12/11/19 05:40', '95752ef1-303f-4992-afda-702585c8793c', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 189)
('12/10/19 15:43', '1306e55e-9757-40a3-9b97-74144840f561', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 302)
('12/10/19 23:05', '1ae5c63c-4c89-4dac-88d9-1d634035d971', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 170)
('13/10/19 01:52', 'eb9fa2a2-3a14-4ce0-a131-5ef493095dca', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 73)
('13/09/19 01:21', '067c7c2d-e6ff-46d4-a6f4-0cea00e94182', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 170)
('13/09/19 05:04', '366f1306-d33f-440d-9831-e9746ac39835', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 170)
('13/09/19 05:23', '236a37a6-6d0e-4932-a6a0-ece76cd5771c', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 146)
('14/08/19 05:41', 'e343d588-643e-4952-a37f-5d21fb2bc159', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 183)
('14/08/19 06:05', 'dd652a99-5df3-451c-9456-3ed00d265e5e', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 123)
('14/08/19 06:07', 'c1a8ffe6-7cfe-42cc-9b5d-89ddf7242a2b', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 221)
('14/07/19 12:18', '22ffa6d8-0702-4020-aa51-5fc312230fa9', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 392)
('15/07/19 01:48', '647a9bdf-97a7-4259-8189-258fed9643bb', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 261)
('15/07/19 05:10', '0d4fa42b-376c-4019-a3a6-a76009ab95e3', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 71)
('15/06/19 02:53', 'bbb5a2fe-fde1-43c8-b8bc-b881cedc9f6a', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 272)
('15/06/19 05:29', '0ce77eac-fa38-4cfd-af55-f51637172306', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 72)
('15/06/19 05:57', '509a136d-684d-413d-8e78-b23b61d87bf8', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 295)
('15/05/19 16:14', 'dda3be20-68a9-4119-967d-52b5fbfd3e9a', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 108)
('15/05/19 18:41', 'f288efdf-c78a-47f0-89da-99e7125582cf', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 160)
('16/05/19 05:36', 'fada2456-d5b4-40f7-963f-60b0d3aba72c', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 342)
('15/04/19 12:01', '068d254b-16d2-4c46-8fd9-fa71d72a1207', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 182)
('15/04/19 20:56', 'bb2c78b4-26a4-4064-bb8d-b6fb55bafaa1', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 320)
('16/04/19 04:26', 'b299ed21-f77b-44cc-bb17-5e564530fb1c', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 146)
('16/03/19 07:12', '4b036ed4-b2d1-4a41-81c7-7751ec8104f9', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 121)
('17/03/19 02:57', '6c7439eb-e86f-4763-a79a-eef2b8392e68', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 280)
('17/03/19 04:16', 'fadcd83f-f27e-4467-b986-3233de0714c7', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 239)
('14/02/19 09:17', 'e9525721-95ad-4d27-9029-a1cadc52aa2e', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 119)
('14/02/19 22:40', 'd2026536-b017-4e66-91a3-ce05202fedb8', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 263)
('14/02/19 22:42', 'c9ca92ed-a32e-46db-a6ef-60fe0cd7c0db', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 204)
('15/01/19 22:04', '6bcb24df-241f-4313-a986-1e88fc2c2319', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 144)
('16/01/19 01:08', '492a8270-b3c5-4573-8577-52be2407e7b9', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 118)
('16/01/19 05:58', '9a141bde-9a8f-4ca6-b446-853a7e275dcd', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 314)
('16/12/18 14:44', 'b73ba9aa-19e3-4b42-86bf-802564e56484', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 195)
('16/12/18 18:36', '93ff2f23-8095-4bab-a524-3f4c73a97cb9', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 152)
('17/12/18 05:08', 'bef2b093-c9db-4113-9049-2ccf81f3d7bc', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 135)
('16/11/18 10:09', '799fca2b-f73d-4fb2-a647-5e6829182a75', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 334)
('17/11/18 01:10', '1c11805f-a6ac-4b51-8e62-15dd96dd570b', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 110)

('17/11/18 02:39', '94be7994-b063-4f15-a045-34eb5b7e889a', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 232)
('17/10/18 14:36', '1cd11ea2-11f1-4dd2-9c58-795354d5e5f9', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 141)
('17/10/18 17:20', '4446739b-9a4f-4fe3-b5d4-51d2b780bf44', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 67)
('17/10/18 23:30', '1d3a2166-ece9-4448-9ba0-cfcc595c7b24', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 186)
('17/09/18 08:36', '20ef6e3f-c003-4b42-a5b5-63672a7b44f8', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 216)
('18/09/18 02:24', '5864ea6d-b64b-4e93-9085-92ac9168814c', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 260)
('18/09/18 03:16', '19dfbfc4-2ed8-48f8-8fa7-635fcf8dd825', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 108)
('18/08/18 18:47', 'cca5e600-7f6a-4bd9-86fa-678889ad302c', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 264)
('19/08/18 05:07', '010191a9-961b-49fe-8a25-18b37a73a5aa', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 96)
('19/08/18 05:55', '431a8c7d-4af1-4b85-885b-4b4d953ef29b', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 367)
('19/07/18 16:16', '2bd97f3f-2189-4c14-907a-0a0522bb08db', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 278)
('20/07/18 01:09', '9700d9a2-539f-4716-8867-682d4f33146f', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 66)
('20/07/18 02:40', 'def11284-0fb1-45df-a163-c0a7ff3fbe65', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 359)
('19/06/18 06:53', '9f397798-e130-499b-aedb-6c3b1feb6aa2', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 282)
('19/06/18 23:18', 'b92c5ed5-d2d7-4051-9bd1-b4d856160b6d', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 72)
('20/06/18 05:34', 'e85333c9-289a-48c9-aeb2-482a4a3d3023', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 241)
('20/05/18 12:09', '9dc2457b-d9b6-4727-a058-13b83569f43d', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 135)
('21/05/18 05:36', 'c109d4c1-ef52-4f09-ba7c-2a812b251d1b', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 277)
('21/05/18 05:36', '5c224456-ccef-4a57-8a06-c98ba30488a6', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 294)
('20/04/18 10:36', '5f616339-3000-41f8-b7ce-9c82b7613559', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 226)
('20/04/18 18:16', 'e4e35642-c02d-4526-9ba2-996315159b9c', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 100)
('21/04/18 01:33', '1807b40d-6760-4a37-b0e4-a90fc07e89c9', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 401)
('21/03/18 23:44', '188a93ef-8d44-4174-9535-1635824b14cc', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 68)
('22/03/18 01:43', 'dee675d2-384d-4f96-8a5d-fd5b39427a80', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 260)
('22/03/18 02:27', 'fd5db53a-53e1-4ef3-bba8-81cd5a5b9517', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 243)
('19/02/18 21:12', '8c707cd5-4e3c-4df5-9031-25d7fe989396', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 61)
('20/02/18 03:34', 'e6a72b91-afad-4154-be13-abd224b6eadf', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 275)
('20/02/18 03:54', '0746af48-236e-4388-9e42-1e2506a3d0da', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 221)
('20/01/18 06:59', '0ee89308-9687-4da7-a0ac-6e0397399bd2', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 258)
('20/01/18 16:28', '24f6f68b-d037-4af2-9a40-63abba3717fa', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 120)
('21/01/18 00:57', 'beee2f05-c050-4268-a09f-50ffd6c054da', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 408)
('21/12/17 20:03', '955ffe89-eeb0-4e94-b37d-49a94b57f43d', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 104)
('21/12/17 21:23', '8471612c-9caa-4d0b-9d19-ff28497e9c13', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 125)
('22/12/17 05:50', 'd8ea5bc7-e48e-47b1-9405-842410dea201', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 425)
('22/11/17 02:47', '5b642907-941d-4fc2-b109-2db4085c777b', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 236)
('22/11/17 03:34', '300ba8e0-5d73-400b-9338-6284a305ba90', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 126)
('22/11/17 04:19', 'a35324d3-9cbb-4ca8-8569-d7bd74b74c19', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 376)
('22/10/17 13:47', '7fc0b76f-494a-4ea2-896b-765f274d86bd', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 208)
('22/10/17 23:21', 'c595a3b0-a55a-411d-bac9-dcb936bdbab7', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 234)
('23/10/17 00:59', '086cad51-5e5a-4391-b404-2db249b52411', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 124)
('23/09/17 01:54', 'fff636f6-850c-44c5-8028-452a534c3333', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 164)
('23/09/17 03:13', '9b790adc-691d-4034-b5c1-3adeb1748fce', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 105)
('23/09/17 03:47', 'fca7a730-2279-4c5f-b5d5-565263c34790', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 52)
('23/08/17 07:28', '2943f076-6321-4fd4-a06d-79223b527779', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 259)
('24/08/17 05:34', '941729dc-09da-42c4-ae70-e8618ed93b03', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 308)
('24/08/17 06:02', '2004ab09-a62b-4e78-80c3-a895acd190d2', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 52)
('24/07/17 09:40', '04d66120-14c4-4233-a9aa-5c90ede2ae25', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 121)
('25/07/17 03:13', '58b3a0c7-838a-4473-b910-bb682e3d291e', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 426)
('25/07/17 04:17', '601b7911-40f5-4864-ad98-205065b5c734', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 154)
('24/06/17 22:56', '613fdae6-ea2b-48a6-924f-99d5a3bc01c4', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 116)
('24/06/17 23:11', 'c90fdb0b-0722-4499-9f6e-0c55df97a753', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 84)
('25/06/17 03:30', '9c0f1f0d-07f4-43b7-9fa1-d96b285d8154', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 235)
('25/05/17 23:49', '27274f6e-18df-4a01-9ab9-948b2708047e', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 333)
('26/05/17 05:06', 'c190815d-e225-40ac-8d4a-ab6d62a79d69', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 86)
('26/05/17 05:51', '493d9f27-3753-4b16-8bf3-629d57e71335', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 131)
('25/04/17 12:12', '1893e106-bf71-4374-b70a-23370336f142', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 124)
('25/04/17 15:53', '18487038-b8a9-424e-9096-35807fb8ef57', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 136)
('26/04/17 02:54', 'f34be0a5-2364-4945-a3d0-027f6e34f2ee', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 197)
('26/03/17 18:10', '2c713247-b860-40e8-9832-04789ad61a7c', 'c53fa27e-c8c2-4b77-a89a-6ed11fa87317', 'Cincinatti', 349)
('27/03/17 04:54', '056cb0d9-599d-4492-ae44-a2ca70f54b6d', 'd20009ca-5479-4232-8b07-7c8c11f74c2e', 'St Louis', 132)
('27/03/17 06:00', 'f577ed6e-d6ff-4ace-9133-15adc6e0eaa5', '70080304-afa3-4026-9c86-95970c4ed5b4', 'Chicago', 111)

NameError: name 'connection' is not defined